Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'spec/**/**'
    - 'db/**/**'
    - 'bin/**'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 18
