default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: <%= ENV['PGPASSWORD'] %>
test:
  <<: *default
  database: manager-stores_test
  host: db
development:
  <<: *default
  database: manager-stores_development
  host: db
production:
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  pool: 15
